title: Charnsak Srisawatsakul, Ph.D.
url: "https://me.charnsak.com"
baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: no
footer_url: "https://github.com/charnsak"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Publications"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
 - name: "Blog"
   link: "https://www.charnsak.com"
